### ISSUE TITLE
Rethink the concept of 'publishing' composite resources

### ISSUE THREAD

**Issue by negz** [crossplane/example-cnp#15]
This sketch currently proposes that a `CompositeResourceDefinition` include the following `spec` fields:

```yaml
  # This policy is equivalent to the existing InfrastructurePublication. Making
  # this a field of the InfrastructureDefinition implies that the package author
  # controls the publication of packaged types; it cannot easily be overridden
  # without forking/duplicating the package. The options are 'Private' (the
  # default), or 'Published'.
  publicationPolicy: Published
  # Publishing a composite resource defines a namespaced proxy of the composite
  # resource. The group, version, and schema of this resource is identical to
  # those of the composite resource but its kind must differ. Conceptually this
  # is a 'published composite resource', rather than 'a requirement'.
  publishedNames:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
```

Per @grantgumina in https://github.com/crossplane/example-cnp/pull/11/files/c726e35421c6ca3ed13e0e4878d0127fd1e64bf5#r470700760:

> I suggest renaming this. Jan and Tim were both confused by the work "publication" showing up here, they thought this either applied to the package or thought this interacted with K8s RBAC in some way.
