### ISSUE TITLE
Consider declaring dependencies on Configurations and Providers explicitly

### ISSUE THREAD

**Issue by hasheddan** [crossplane/example-cnp#8]
I ran into this today while working on the package manager where I had a `Configuration` with dependencies on a `Provider`. The a `Configuration` was created in the cluster, but when the controller read the dependencies of that `Configuration` and went to install them, it didn't know whether to create the depended upon package as a `Provider` or a `Configuration`. One way to work around this is to unpack the dependency first, see which type of package it is, then create that type. However, if we are explicitly distinguishing these package type it may make more sense to just declare provider dependencies and configuration dependencies separately.

**Comment by negz** [comment]
@hasheddan Are you thinking something like:


```yaml
spec:
  dependsOn:
  - configuration: exampleco/cnp-eks
    version: "0.1.0"
  - configuration: exampleco/cnp-fluentbit
    version: "0.1.0"
```

Where one could write `provider` instead of `configuration`?
